### ISSUE TITLE
Fatal error on due to missing cast

### ISSUE THREAD

**Issue by jonasraoni** [pkp/quickSubmit#81]
Reference: https://github.com/pkp/pkp-lib/issues/9821

```
PHP Fatal error:  Uncaught TypeError: PKP\section\Repository::exists(): Argument #1 ($id) must be of type int, string given, called in /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.php on line 86 and defined in /var/www/html/ojs/lib/pkp/classes/section/Repository.php:52
Stack trace:
#0 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.php(86): PKP\section\Repository->exists()
#1 [internal function]: APP\plugins\importexport\quickSubmit\QuickSubmitForm->APP\plugins\importexport\quickSubmit\{closure}()
#2 /var/www/html/ojs/lib/pkp/classes/form/validation/FormValidatorCustom.php(83): call_user_func_array()
#3 /var/www/html/ojs/lib/pkp/classes/form/Form.php(290): PKP\form\validation\FormValidatorCustom->isValid()
#4 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.php(223): PKP\form\Form->validate()
#5 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(177): APP\plugins\importexport\quickSubmit\QuickSubmitForm->validate()
#6 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(67): APP\plugins\importexport\quickSubmit\QuickSubmitPlugin->_saveSubmit()
#7 /var/www/html/ojs/lib/pkp/pages/management/PKPToolsHandler.php(104): APP\plugins\importexport\quickSubmit\QuickSubmitPlugin->display()
#8 [internal function]: PKP\pages\management\PKPToolsHandler->importexport()
#9 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#10 /var/www/html/ojs/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#11 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#12 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch()
#13 /var/www/html/ojs/index.php(21): PKP\core\PKPApplication->execute()
#14 {main}
  thrown in /var/www/html/ojs/lib/pkp/classes/section/Repository.php on line 52
```

**PRs**
- https://github.com/pkp/quickSubmit/pull/82
- https://github.com/pkp/quickSubmit/pull/83

**Comment by jonasraoni** [comment]
Hi @bozana! Could you review the PR below?

As there's formatting included, I think it's better to watch the individual commits before formatting.
- https://github.com/pkp/quickSubmit/pull/82

**Comment by bozana** [comment]
Hi @jonasraoni, yes, all fine (I hope formatting commit is all fine :sweat_smile:). Could you port it to main too?

**Comment by jonasraoni** [comment]
Hi @bozana, here's the PR for main and additional updates for the stable-3_4_0:
- https://github.com/pkp/quickSubmit/pull/83
- https://github.com/pkp/quickSubmit/pull/84
